FROM ufoym/deepo:py36-cu90

# Python 2.7 or 3.6 is supported by Ubuntu Bionic out of the box
ARG python=3.6

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]
ADD sources.list /etc/apt/sources.list

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U \
    && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple


RUN apt-get update && apt-get install -y --allow-downgrades --allow-change-held-packages --no-install-recommends \
        build-essential \
        cmake \
        g++-4.8 \
        libffi-dev \
        libssl-dev \
        python-dev \
        libpng-dev

# Install python package
RUN pip install efficientnet_pytorch && \
    pip install nonechucks && \
    pip install tensorboardX && \
    pip install tqdm && \
    pip install keras-rectified-adam && \
    pip install git+https://www.github.com/keras-team/keras-contrib.git

# Install Open MPI

RUN mkdir /tmp/openmpi && \
    cd /tmp/openmpi && \
    wget -e use_proxy=on -e http_proxy=http://proxy.p1staff.com:1337 https://www.open-mpi.org/software/ompi/v4.0/downloads/openmpi-4.0.0.tar.gz && \
    tar zxf openmpi-4.0.0.tar.gz && \
    cd openmpi-4.0.0 && \
    ./configure --enable-orterun-prefix-by-default && \
    make -j $(nproc) all && \
    make install && \
    ldconfig && \
    rm -rf /tmp/openmpi

# Install Horovod, temporarily using CUDA stubs
RUN ldconfig /usr/local/cuda/targets/x86_64-linux/lib/stubs && \
    HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_TENSORFLOW=1 \
         pip install --no-cache-dir horovod && \
    ldconfig

# Install OpenSSH for MPI to communicate between containers
RUN apt-get install -y --no-install-recommends openssh-client openssh-server && \
    mkdir -p /var/run/sshd

# Allow OpenSSH to talk to containers without asking for confirmation
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

# Download examples
RUN apt-get install -y --no-install-recommends subversion && \
    svn checkout https://github.com/horovod/horovod/trunk/examples && \
    rm -rf /examples/.svn

# Add rsa key
# ADD --chown=root:root ~/id_rsa /root/.ssh/id_rsa
#
# ADD --chown=root:root authorized_keys /root/.ssh/authorized_keys
#
# RUN chmod 700 /root/.ssh && \
#     chmod 600 /root/.ssh/authorized_keys


WORKDIR "/examples"